### ISSUE TITLE
Import from Postman Version 4.3.2 fails

### ISSUE THREAD

**Issue by mllanes** [luckymarmot/Paw-PostmanImporter#13] opened 2016-06-12 19:42 UTC
In postman: settings-->data-->Export Data:

![screen shot 2016-06-12 at 12 41 53 pm](https://cloud.githubusercontent.com/assets/2744135/15993436/1001d4f2-309b-11e6-841b-93aa219aee25.png)

Generates a json file that although valid (checked with json lint) can not be imported into PAW; the following error is thrown when going File-->Import -->File

![screen shot 2016-06-12 at 12 40 50 pm](https://cloud.githubusercontent.com/assets/2744135/15993427/e48ec4f6-309a-11e6-8b44-ad95f2037d42.png)

Paw Version 2.2.5

**Comment by JonathanMontane** [comment] 2016-06-13 07:19
hi @mllanes, we are aware of the issue and are working on fixing it. Last week, Postman changed the way it stores its data to a completely new format ([old](https://schema.getpostman.com/json/collection/v1/collection.json)/[new](https://schema.getpostman.com/json/collection/v2.0.0/collection.json)) and that naturally broke our importer.

We are in the process of creating a format conversion tool, called [API-Flow](https://github.com/luckymarmot/API-Flow), that should help you convert Swagger/RAML/Postman/cURL/etc. into one another. We are currently implementing the v2 for Postman, and the project is still under development, but this may help you. It should work as a CLI, as a web library and in Paw (with the next release).

The documentation is lacking atm (working on it), so here are a few critical steps that should get you going:

```sh
git clone https://github.com/luckymarmot/API-Flow.git
git checkout 038-v0.1
npm install
babel-node ./src/flow-node.js [local/file/to/parse] --from [source format: e.g. postman-2] --to [target format: e.g. swagger] > converted.json
```

ATM, this should not work (still fixing bugs in postman-2), but I'll keep you updated for when we have a somewhat stable solution.

**Comment by nLamprok** [comment] 2016-06-24 10:13
Any news on that?

**Comment by Isuru-Nanayakkara** [comment] 2016-07-02 13:31
+1

**Comment by joshuakelly** [comment] 2016-07-19 02:28
Waiting on an update for this.

**Comment by mcetin71** [comment] 2016-07-24 01:46
+1

**Comment by Tibimac** [comment] 2016-07-27 13:12
+1 🙂 
Good work guys !

**Comment by JonathanMontane** [comment] 2016-07-28 13:14
The new Importer (released 2016-06-28) should fix most issues, and should support both old files and new files. If there are still issues (likely), don't hesitate to create an issue.

**Comment by Prince2k3** [comment] 2016-07-28 14:03
@JonathanMontane The release posted still doesn't work.

**Comment by JonathanMontane** [comment] 2016-07-28 14:54
Interesting, would you mind sending us a failing file so that we can investigate more in depth on our end? Are you on the newest release of Paw (Paw 3)? If not, you shouldn't have been able to get access to the newest release, as it uses Promises, which were not supported in previous versions.

**Comment by Prince2k3** [comment] 2016-07-28 15:05
Yeah I will try the paw 3. Just noticed the website changed when I went back to it to check the version.

**Comment by Prince2k3** [comment] 2016-07-28 15:06
Yeah paw 3 works just fine... Thanks!

**Comment by JonathanMontane** [comment] 2016-07-28 15:10
@Prince2k3 Glad to see that the issue is resolved for you! There might still be quite a few issues as we changed a LOT of things in this release.

**Comment by Prince2k3** [comment] 2016-07-28 15:11
@JonathanMontane This release is nice. Can't wait to see what it can do!

**Comment by mllanes** [comment] 2016-07-30 01:08
so with Postman 4.4.3 and Paw 3.0.4 it fails now with the following error:
'...A JavaScript exception was raised. Open the Extension Console (under the Window menu) for more information..."

And the console:
JS Exception Line 86963. TypeError: Invalid attempt to destructure non-iterable instance

**Comment by mcetin71** [comment] 2016-07-30 15:38
same here

**Comment by JonathanMontane** [comment] 2016-08-03 08:00
First issue is fixed. Second issue should be fixed too (it was unrelated - Sometimes, digest auth headers were corrupted in postman collections).
@mllanes @mcetin71 tell me if you still encounter any issue related to these two specific issues.
Feel free to open new issues too!

**Closed by JonathanMontane** 2016-08-03 08:00 UTC

**Comment by mcetin71** [comment] 2016-08-03 14:19
i am still seeing the issue with the non-iterable instance. I sent my exported file to support, so you guys should be able to test it on your side as well.

**Comment by JonathanMontane** [comment] 2016-08-03 15:47
@mcetin71 should be fixed now. Thank your for the file, it helped us find the bug! (weird authorization header only containing a space character caused the crash)

**Comment by mcetin71** [comment] 2016-08-03 17:34
yes, it works. Thanks!
